### ISSUE TITLE
Organizational Testing with Jekyll Actions Quickstart Does Not Work

### ISSUE THREAD

**Issue by oDinZu** [MichaelCurrin/jekyll-actions-quickstart#3]
I wanted to see a good example on how this works. 

I have been having lots of resistance with getting an organizational GH pages and Jekyll Actions up and running with custom plugins these past two days. 

I discovered, even this simple quickstart fork, does not work on my org. account and provides the same exact errors. 
What is it that I am doing wrong?

Logs posted below:
```
error: src refspec ***@github.com/Galactic-Society/jekyll-actions-quickstart.git does not match any
error: failed to push some refs to 'https://'
```

**Comment by MichaelCurrin** [comment]
Its seems build failed to push after committing

https://github.com/Galactic-Society/jekyll-actions-quickstart/runs/1039442135

Did you set the token value? That is needed for the workflow to have access to push to your branch.

https://github.com/MichaelCurrin/jekyll-actions-quickstart#deployment

**Comment by MichaelCurrin** [comment]
Or you secret added to your repo has insufficient permissions.

If you're still stuck, Netlify is super easy to run custom gems. Import into [netlify.com](https://netlify.com) and it will install from your Gemfile and run your build command. Much lighter than an Actions config and no token needed

https://github.com/MichaelCurrin/code-cookbook/blob/master/recipes/ci-cd/netlify/configure.md
